-- Statusline = {}
--
-- -- At the start of the file
-- local state = {
-- 	show_path = true,
-- }
--
-- local config = {
-- 	icons = {
-- 		path_hidden = "", -- opened directory icon
-- 	},
-- }
--
-- local function git()
-- 	local git_info = vim.b.gitsigns_status_dict
-- 	if not git_info or git_info.head == "" then
-- 		return ""
-- 	end
--
-- 	local head = git_info.head
-- 	local added = git_info.added and (" +" .. git_info.added) or ""
-- 	local changed = git_info.changed and (" ~" .. git_info.changed) or ""
-- 	local removed = git_info.removed and (" -" .. git_info.removed) or ""
-- 	if git_info.added == 0 then
-- 		added = ""
-- 	end
-- 	if git_info.changed == 0 then
-- 		changed = ""
-- 	end
-- 	if git_info.removed == 0 then
-- 		removed = ""
-- 	end
--
-- 	return table.concat({
-- 		"[ ", -- branch icon
-- 		head,
-- 		added,
-- 		changed,
-- 		removed,
-- 		"]",
-- 	})
-- end
--
-- local function lsp_client()
-- 	local bufnr = vim.api.nvim_get_current_buf()
--
-- 	local clients = vim.lsp.get_clients({ bufnr = bufnr })
--
-- 	if next(clients) == nil then
-- 		return ""
-- 	end
--
-- 	local c = {}
--
-- 	for _, client in pairs(clients) do
-- 		table.insert(c, client.name)
-- 	end
--
-- 	return "[\u{f085} " .. table.concat(c, "|") .. "]"
-- end
--
-- local function filepath()
-- 	-- Modify the given file path with the given modifiers
-- 	local fpath = vim.fn.fnamemodify(vim.fn.expand("%"), ":~:.:h")
--
-- 	if fpath == "" or fpath == "." then
-- 		return ""
-- 	end
--
-- 	if state.show_path then
-- 		local fullPath = vim.fn.has("macunix") == 1 and string.format("%%<%s/", fpath)
-- 			or string.format("%%<%s\\", fpath)
-- 		return fullPath
-- 	end
--
-- 	return config.icons.path_hidden .. "/"
-- 	-- `%%` -> `%`.
-- 	-- `%s` -> value of `fpath`.
-- 	-- The result is `%<fpath/`.
-- 	-- `%<` tells where to truncate when there is not enough space.
-- end
--
-- function Statusline.active()
-- 	-- `%P` shows the scroll percentage but says 'Bot', 'Top' and 'All' as well.
-- 	-- return "[%f]%=%y [ %l:%c]"
-- 	return table.concat({ "[", filepath(), "%t] ", git(), "%=", "%y ", lsp_client(), " [%l:%c]" })
-- end
--
-- function Statusline.inactive()
-- 	return " %t"
-- end
--
-- local group = vim.api.nvim_create_augroup("Statusline", { clear = true })
--
-- vim.api.nvim_create_autocmd({ "WinEnter", "BufEnter" }, {
-- 	group = group,
-- 	desc = "Activate statusline on focus",
-- 	callback = function()
-- 		vim.opt_local.statusline = "%!v:lua.Statusline.active()"
-- 	end,
-- })
--
-- vim.api.nvim_create_autocmd({ "WinLeave", "BufLeave" }, {
-- 	group = group,
-- 	desc = "Deactivate statusline when unfocused",
-- 	callback = function()
-- 		vim.opt_local.statusline = "%!v:lua.Statusline.inactive()"
-- 	end,
-- })
--
-- vim.keymap.set("n", "<leader>gsp", function()
-- 	Statusline.toggle_path()
-- end, { desc = "Toggle statusline path" })
